<a href="https://colab.research.google.com/github/srujanperam/dl_1/blob/srujan_regex/Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import pandas as pd
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [2]:
ls

sample_data/


In [3]:
pwd

'/content'

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/DeepLearningML/6_gradient_descent/insurance_data.csv')

In [5]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df[['age', 'affordibility']], df.bought_insurance,
    test_size=0.2, random_state =2
)

In [7]:
X_train

age  affordibility
16   25              0
6    55              0
3    52              0
21   26              0
26   23              1
25   54              1
12   27              0
4    46              1
10   18              1
5    56              1
20   21              1
2    47              1
7    60              0
24   50              1
23   45              1
18   19              0
11   28              1
22   40              1
27   46              1
13   29              0
15   55              1
8    62              1

In [8]:
len(X_train)

22

In [9]:
df.shape

(28, 3)

In [10]:
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()
X_train_scaled['age'] = X_train_scaled['age']/100
X_test_scaled['age'] = X_test_scaled['age']/100

In [11]:
model = keras.Sequential([keras.layers.Dense(1,
                                             input_shape=(2,),
                                             activation='sigmoid',
      kernel_initializer='ones', bias_initializer='zeros')])

In [12]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [13]:
# fro hight the epochs, runtime is taking much time, so reduced to epochs 10
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 2ms/step - loss: 0.7146 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 2ms/step - loss: 0.7142 - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 2ms/step - loss: 0.7138 - accuracy: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 0.7135 - accuracy: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 1ms/step - loss: 0.7131 - accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 0.7127 - accuracy: 0.5000
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 0.7123 - accuracy: 0.5000
Epoch 8/10
1/1 [==============================] - 0s 2ms/step - loss: 0.7119 - accuracy: 0.5000
Epoch 9/10
1/1 [==============================] - 0s 2ms/step - loss: 0.7116 - accuracy: 0.5000
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 0.7112 - accuracy: 0.5000


In [14]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 1ms/step - loss: 0.7163 - accuracy: 0.5000


[0.7163488268852234, 0.5]

In [15]:
model.predict(X_test_scaled)

array([[0.5590993 ],
       [0.7681359 ],
       [0.81231415],
       [0.8297588 ],
       [0.76100814],
       [0.8255222 ]], dtype=float32)

In [16]:
model.predict(X_test_scaled)

array([[0.5590993 ],
       [0.7681359 ],
       [0.81231415],
       [0.8297588 ],
       [0.76100814],
       [0.8255222 ]], dtype=float32)

In [17]:
y_test

1     0
0     0
14    1
9     1
19    0
17    1
Name: bought_insurance, dtype: int64

In [18]:
coef, intercept = model.get_weights()

In [19]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [20]:
X_test

age  affordibility
1    25              0
0    22              1
14   49              1
9    61              1
19   18              1
17   58              1

In [21]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

prediction_function(.47, 1)

0.8092767474766774

In [22]:
prediction_function(.18, 1)

0.7610081847462706

In [23]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [24]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [25]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [27]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000, 0.4631)

Epoch:0, w1:0.973391914875179, w2:0.9484790550524685, bias:-0.11334365204477419, loss:0.714610156590683
Epoch:1, w1:0.9526050112606814, w2:0.9061888855737805, bias:-0.21202325373024938, loss:0.6844545754122794
Epoch:2, w1:0.9371389216394038, w2:0.8724863718378795, bias:-0.29735477734867394, loss:0.6623114062843336
Epoch:3, w1:0.9263972300850559, w2:0.8464964034855741, bias:-0.3708685783767046, loss:0.6463299135248588
Epoch:4, w1:0.9197530021886515, w2:0.8272363836850969, bias:-0.4341501414207024, loss:0.6349055537023248
Epoch:5, w1:0.9165978234998884, w2:0.8137152861544186, bias:-0.48872346395231214, loss:0.6267483980102484
Epoch:6, w1:0.9163723575035057, w2:0.804999539668341, bias:-0.5359802497218649, loss:0.6208785684684357
Epoch:7, w1:0.9185813941347364, w2:0.8002492021116546, bias:-0.5771466732016118, loss:0.6165824439197473
Epoch:8, w1:0.9227979840062284, w2:0.7987322635165252, bias:-0.6132761019356342, loss:0.6133562082414478
Epoch:9, w1:0.9286609028533963, w2:0.7998249643661494,

(5.776540098602374, 1.5072936283526548, -3.292466234362901)

In [28]:
coef, intercept

(array([[0.9900094],
        [0.9900079]], dtype=float32), array([-0.00999473], dtype=float32))