<a href="https://colab.research.google.com/github/srujanperam/dl_1/blob/main/notebooks/Loss_or_Cost_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [28]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [6]:
def mae(y_true, y_predicted):
  # total_error = 0
  # for yt, yp in zip(y_true, y_predicted):
  #   total_error += abs(yt-yp)
  # mae = total_error/len(y_true) 
  return np.mean(np.abs(y_true-y_predicted))

In [7]:
mae(y_true, y_predicted)

0.5

In [13]:
def mse(y_true, y_predicted):
  return np.mean(np.square(y_true-y_predicted))

In [14]:
mse(y_true, y_predicted)

0.366

In [12]:
np.log([0])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [17]:
np.log([0.0000000000000000000000001])

array([-78.28789316])

In [46]:
# log loss or binary cross entropy
epsilon = 1e-15

In [47]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [48]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new = np.array(y_predicted_new)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [49]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [52]:
def log_loss(y_true, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i,epsilon) for i in y_predicted]
  y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [53]:
log_loss(y_true, y_predicted)

17.2696280766844